// tslint:disable
/**
 * Octopus Energy
 * This is Rocketmakers implementation of the Octopus Energy API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@rocketmakers.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ProductLinks
 */
export interface ProductLinks {
    /**
     * Link to single product
     * @type {string}
     * @memberof ProductLinks
     */
    href: string;
    /**
     * HTTP Method
     * @type {string}
     * @memberof ProductLinks
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof ProductLinks
     */
    rel: string;
}
/**
 * 
 * @export
 * @interface ProductObject
 */
export interface ProductObject {
    /**
     * Product Code
     * @type {string}
     * @memberof ProductObject
     */
    code: string;
    /**
     * Full name of product
     * @type {string}
     * @memberof ProductObject
     */
    full_name: string;
    /**
     * Display name of product
     * @type {string}
     * @memberof ProductObject
     */
    display_name: string;
    /**
     * Description of product
     * @type {string}
     * @memberof ProductObject
     */
    description: string;
    /**
     * Is the product Variable
     * @type {boolean}
     * @memberof ProductObject
     */
    is_variable: boolean;
    /**
     * Is the product Green
     * @type {boolean}
     * @memberof ProductObject
     */
    is_green: boolean;
    /**
     * Is the product Tracker
     * @type {boolean}
     * @memberof ProductObject
     */
    is_tracker: boolean;
    /**
     * Is the product Prepay
     * @type {boolean}
     * @memberof ProductObject
     */
    is_prepay: boolean;
    /**
     * Is the product is for Businesses
     * @type {boolean}
     * @memberof ProductObject
     */
    is_business: boolean;
    /**
     * Is the product Restricted
     * @type {boolean}
     * @memberof ProductObject
     */
    is_restricted: boolean;
    /**
     * Is the number of months that a product lasts for if it is fixed length
     * @type {number}
     * @memberof ProductObject
     */
    term: number;
    /**
     * Brand Name
     * @type {string}
     * @memberof ProductObject
     */
    brand: string;
    /**
     * Product available from
     * @type {string}
     * @memberof ProductObject
     */
    available_from: string;
    /**
     * Product available to
     * @type {string}
     * @memberof ProductObject
     */
    available_to: string;
    /**
     * 
     * @type {Array<ProductLinks>}
     * @memberof ProductObject
     */
    links: Array<ProductLinks>;
}
/**
 * 
 * @export
 * @interface ProductWithTariffsObject
 */
export interface ProductWithTariffsObject {
    /**
     * Product Code
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    code: string;
    /**
     * Full name of product
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    full_name: string;
    /**
     * Display name of product
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    display_name: string;
    /**
     * Description of product
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    description: string;
    /**
     * Is the product Variable
     * @type {boolean}
     * @memberof ProductWithTariffsObject
     */
    is_variable: boolean;
    /**
     * Is the product Green
     * @type {boolean}
     * @memberof ProductWithTariffsObject
     */
    is_green: boolean;
    /**
     * Is the product Tracker
     * @type {boolean}
     * @memberof ProductWithTariffsObject
     */
    is_tracker: boolean;
    /**
     * Is the product Prepay
     * @type {boolean}
     * @memberof ProductWithTariffsObject
     */
    is_prepay: boolean;
    /**
     * Is the product is for Businesses
     * @type {boolean}
     * @memberof ProductWithTariffsObject
     */
    is_business: boolean;
    /**
     * Is the product Restricted
     * @type {boolean}
     * @memberof ProductWithTariffsObject
     */
    is_restricted: boolean;
    /**
     * Is the number of months that a product lasts for if it is fixed length
     * @type {number}
     * @memberof ProductWithTariffsObject
     */
    term: number;
    /**
     * Brand Name
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    brand: string;
    /**
     * Product available from
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    available_from: string;
    /**
     * Product available to
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    available_to: string;
    /**
     * Tariff available at
     * @type {string}
     * @memberof ProductWithTariffsObject
     */
    tariffs_active_at?: string;
    /**
     * 
     * @type {SampleConsumption}
     * @memberof ProductWithTariffsObject
     */
    sample_consumption: SampleConsumption;
    /**
     * 
     * @type {Array<ProductLinks>}
     * @memberof ProductWithTariffsObject
     */
    links: Array<ProductLinks>;
}
/**
 * 
 * @export
 * @interface Products
 */
export interface Products {
    /**
     * Results in Response
     * @type {number}
     * @memberof Products
     */
    count: number;
    /**
     * Paginated URL for next records
     * @type {string}
     * @memberof Products
     */
    next: string;
    /**
     * Paginated URL for previous records
     * @type {string}
     * @memberof Products
     */
    previous: string;
    /**
     * 
     * @type {Array<ProductObject>}
     * @memberof Products
     */
    results: Array<ProductObject>;
}
/**
 * 
 * @export
 * @interface SampleConsumption
 */
export interface SampleConsumption {
    /**
     * 
     * @type {SampleConsumptionElectricitySingleRate}
     * @memberof SampleConsumption
     */
    electricity_single_rate: SampleConsumptionElectricitySingleRate;
    /**
     * 
     * @type {SampleConsumptionElectricityDualRate}
     * @memberof SampleConsumption
     */
    electricity_dual_rate: SampleConsumptionElectricityDualRate;
    /**
     * 
     * @type {SampleConsumptionDualFuelSingleRate}
     * @memberof SampleConsumption
     */
    dual_fuel_single_rate: SampleConsumptionDualFuelSingleRate;
    /**
     * 
     * @type {SampleConsumptionDualFuelDualRate}
     * @memberof SampleConsumption
     */
    dual_fuel_dual_rate: SampleConsumptionDualFuelDualRate;
}
/**
 * 
 * @export
 * @interface SampleConsumptionDualFuelDualRate
 */
export interface SampleConsumptionDualFuelDualRate {
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionDualFuelDualRate
     */
    electricity_day?: number;
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionDualFuelDualRate
     */
    electricity_night?: number;
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionDualFuelDualRate
     */
    gas_standard?: number;
}
/**
 * 
 * @export
 * @interface SampleConsumptionDualFuelSingleRate
 */
export interface SampleConsumptionDualFuelSingleRate {
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionDualFuelSingleRate
     */
    electricity_standard?: number;
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionDualFuelSingleRate
     */
    gas_standard?: number;
}
/**
 * 
 * @export
 * @interface SampleConsumptionElectricityDualRate
 */
export interface SampleConsumptionElectricityDualRate {
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionElectricityDualRate
     */
    electricity_day?: number;
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionElectricityDualRate
     */
    electricity_night?: number;
}
/**
 * 
 * @export
 * @interface SampleConsumptionElectricitySingleRate
 */
export interface SampleConsumptionElectricitySingleRate {
    /**
     * 
     * @type {number}
     * @memberof SampleConsumptionElectricitySingleRate
     */
    electricity_standard?: number;
}

/**
 * EnergyProductsApi - axios parameter creator
 * @export
 */
export const EnergyProductsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * By default, results will be public energy products but if the authenticated organisations will also see products available to their organisation.
         * @summary Return a list of energy products.
         * @param {boolean} [isVariable] Show only variable products.
         * @param {boolean} [isGreen] Show only green products.
         * @param {boolean} [isPrepay] Show only tracker products.
         * @param {boolean} [isBusiness] Show only business products.
         * @param {string} [availableAt] Show products available for new agreements on the given datetime. Defaults to current datetime, effectively showing products that are currently available.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsGet: async (isVariable?: boolean, isGreen?: boolean, isPrepay?: boolean, isBusiness?: boolean, availableAt?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/products`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (isVariable !== undefined) {
                localVarQueryParameter['is_variable'] = isVariable;
            }

            if (isGreen !== undefined) {
                localVarQueryParameter['is_green'] = isGreen;
            }

            if (isPrepay !== undefined) {
                localVarQueryParameter['is_prepay'] = isPrepay;
            }

            if (isBusiness !== undefined) {
                localVarQueryParameter['is_business'] = isBusiness;
            }

            if (availableAt !== undefined) {
                localVarQueryParameter['available_at'] = availableAt;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve the details of a product (including all its tariffs) for a particular point in time.
         * @summary Retrieve the details of a product (including all its tariffs) for a particular point in time.
         * @param {string} productCode The code of the product to be retrieved, for example VAR-17-01-11
         * @param {string} [tariffsActiveAt] The point in time in which to show the active charges. Defaults to current datetime.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsProductCodeGet: async (productCode: string, tariffsActiveAt?: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'productCode' is not null or undefined
            if (productCode === null || productCode === undefined) {
                throw new RequiredError('productCode','Required parameter productCode was null or undefined when calling productsProductCodeGet.');
            }
            const localVarPath = `/products/{product_code}`
                .replace(`{${"product_code"}}`, encodeURIComponent(String(productCode)));
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (tariffsActiveAt !== undefined) {
                localVarQueryParameter['tariffs_active_at'] = tariffsActiveAt;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EnergyProductsApi - functional programming interface
 * @export
 */
export const EnergyProductsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * By default, results will be public energy products but if the authenticated organisations will also see products available to their organisation.
         * @summary Return a list of energy products.
         * @param {boolean} [isVariable] Show only variable products.
         * @param {boolean} [isGreen] Show only green products.
         * @param {boolean} [isPrepay] Show only tracker products.
         * @param {boolean} [isBusiness] Show only business products.
         * @param {string} [availableAt] Show products available for new agreements on the given datetime. Defaults to current datetime, effectively showing products that are currently available.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsGet(isVariable?: boolean, isGreen?: boolean, isPrepay?: boolean, isBusiness?: boolean, availableAt?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Products>> {
            const localVarAxiosArgs = await EnergyProductsApiAxiosParamCreator(configuration).productsGet(isVariable, isGreen, isPrepay, isBusiness, availableAt, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Retrieve the details of a product (including all its tariffs) for a particular point in time.
         * @summary Retrieve the details of a product (including all its tariffs) for a particular point in time.
         * @param {string} productCode The code of the product to be retrieved, for example VAR-17-01-11
         * @param {string} [tariffsActiveAt] The point in time in which to show the active charges. Defaults to current datetime.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsProductCodeGet(productCode: string, tariffsActiveAt?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductWithTariffsObject>> {
            const localVarAxiosArgs = await EnergyProductsApiAxiosParamCreator(configuration).productsProductCodeGet(productCode, tariffsActiveAt, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EnergyProductsApi - factory interface
 * @export
 */
export const EnergyProductsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * By default, results will be public energy products but if the authenticated organisations will also see products available to their organisation.
         * @summary Return a list of energy products.
         * @param {boolean} [isVariable] Show only variable products.
         * @param {boolean} [isGreen] Show only green products.
         * @param {boolean} [isPrepay] Show only tracker products.
         * @param {boolean} [isBusiness] Show only business products.
         * @param {string} [availableAt] Show products available for new agreements on the given datetime. Defaults to current datetime, effectively showing products that are currently available.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsGet(isVariable?: boolean, isGreen?: boolean, isPrepay?: boolean, isBusiness?: boolean, availableAt?: string, options?: any): AxiosPromise<Products> {
            return EnergyProductsApiFp(configuration).productsGet(isVariable, isGreen, isPrepay, isBusiness, availableAt, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve the details of a product (including all its tariffs) for a particular point in time.
         * @summary Retrieve the details of a product (including all its tariffs) for a particular point in time.
         * @param {string} productCode The code of the product to be retrieved, for example VAR-17-01-11
         * @param {string} [tariffsActiveAt] The point in time in which to show the active charges. Defaults to current datetime.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsProductCodeGet(productCode: string, tariffsActiveAt?: string, options?: any): AxiosPromise<ProductWithTariffsObject> {
            return EnergyProductsApiFp(configuration).productsProductCodeGet(productCode, tariffsActiveAt, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EnergyProductsApi - interface
 * @export
 * @interface EnergyProductsApi
 */
export interface EnergyProductsApiInterface {
    /**
     * By default, results will be public energy products but if the authenticated organisations will also see products available to their organisation.
     * @summary Return a list of energy products.
     * @param {boolean} [isVariable] Show only variable products.
     * @param {boolean} [isGreen] Show only green products.
     * @param {boolean} [isPrepay] Show only tracker products.
     * @param {boolean} [isBusiness] Show only business products.
     * @param {string} [availableAt] Show products available for new agreements on the given datetime. Defaults to current datetime, effectively showing products that are currently available.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnergyProductsApiInterface
     */
    productsGet(isVariable?: boolean, isGreen?: boolean, isPrepay?: boolean, isBusiness?: boolean, availableAt?: string, options?: any): AxiosPromise<Products>;

    /**
     * Retrieve the details of a product (including all its tariffs) for a particular point in time.
     * @summary Retrieve the details of a product (including all its tariffs) for a particular point in time.
     * @param {string} productCode The code of the product to be retrieved, for example VAR-17-01-11
     * @param {string} [tariffsActiveAt] The point in time in which to show the active charges. Defaults to current datetime.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnergyProductsApiInterface
     */
    productsProductCodeGet(productCode: string, tariffsActiveAt?: string, options?: any): AxiosPromise<ProductWithTariffsObject>;

}

/**
 * EnergyProductsApi - object-oriented interface
 * @export
 * @class EnergyProductsApi
 * @extends {BaseAPI}
 */
export class EnergyProductsApi extends BaseAPI implements EnergyProductsApiInterface {
    /**
     * By default, results will be public energy products but if the authenticated organisations will also see products available to their organisation.
     * @summary Return a list of energy products.
     * @param {boolean} [isVariable] Show only variable products.
     * @param {boolean} [isGreen] Show only green products.
     * @param {boolean} [isPrepay] Show only tracker products.
     * @param {boolean} [isBusiness] Show only business products.
     * @param {string} [availableAt] Show products available for new agreements on the given datetime. Defaults to current datetime, effectively showing products that are currently available.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnergyProductsApi
     */
    public productsGet(isVariable?: boolean, isGreen?: boolean, isPrepay?: boolean, isBusiness?: boolean, availableAt?: string, options?: any) {
        return EnergyProductsApiFp(this.configuration).productsGet(isVariable, isGreen, isPrepay, isBusiness, availableAt, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve the details of a product (including all its tariffs) for a particular point in time.
     * @summary Retrieve the details of a product (including all its tariffs) for a particular point in time.
     * @param {string} productCode The code of the product to be retrieved, for example VAR-17-01-11
     * @param {string} [tariffsActiveAt] The point in time in which to show the active charges. Defaults to current datetime.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EnergyProductsApi
     */
    public productsProductCodeGet(productCode: string, tariffsActiveAt?: string, options?: any) {
        return EnergyProductsApiFp(this.configuration).productsProductCodeGet(productCode, tariffsActiveAt, options).then((request) => request(this.axios, this.basePath));
    }

}


